### PR TITLE
typescript

### PR DESCRIPTION
**Pull request by dcharbonnier**
The easier way to get typescript definitions, the next step would be to add typings instead of `any` but it does not need to be done all at the same time and it's just an help to prevent bugs.
I will not transform this PR in a troll about ts but as you can see ts is almost javascript and will ever be, there is no learning curve, you know js you know ts.

### CODE REVIEW

**Comment by AgustinCB** [comment]
Anything that adds type safety has my blessing. 

However I can't merge if it breaks the tests and I'd prefer the linter to stay in place. Can you take a look at that please? If you prefer, I can also make these corrections myself, but it'll take me a couple days probably (I'm usually able to spend time in this project over the weekend).

Thank you for your contribution!

**Comment by dcharbonnier** [comment]
yes, will check that, for the linter I'm a fundamentalist but I don't wanted to make a PR that will change all lines even if it's only space. I'm happy to do it :-)

**Comment by dcharbonnier** [comment]
on my machine they pass, can you try a rebuild ? on travis ?

**Comment by AgustinCB** [comment]
Sure! Rebuilding now.

**Comment by AgustinCB** [comment]
Never mind, the problem is related with the travis set up. New versions of docker packages changed a couple things.

You can fix it by cherry picking this commit into your branch: https://github.com/AgustinCB/docker-api/commit/ccf3b6378b8a1c7794dee709860257b4c25e2da7

Sorry about that, my bad.

**Comment by shomodj** [comment]
+1 for move to typescript

**Comment by AgustinCB** [comment]
I prefer some of the options like they were in the previous lint (single quotes strings and no semicolon). But that's a nitpick I can do in a separate pr. So far so good, so will squash and merge this. Thank you so much for this contribution.

**Comment by dcharbonnier** [comment]
arf ok, I forgot to put a WIP, more to come, working on removing the implicit any and adding more typing right now

**Pull request merged**
