### PR TITLE
fix types for object string and number

### LINKED ISSUE #40: wrong types String
We should use `string` and `number` and not `String` and `Number`
https://stackoverflow.com/questions/14727044/typescript-difference-between-string-and-string

### PR DESCRIPTION
**Pull request by dcharbonnier**
close #40

### CODE REVIEW

**Comment by AgustinCB** [comment]
THank you!

**Comment by dcharbonnier** [comment]
If you can release I can avoid using my fork on my project, I can't compile with the current version without ignoring errors :-)

**Comment by AgustinCB** [comment]
I'm at work and I don't have the credentials to release :/. Can it wait about 3 hours?

Sorry!

**Comment by dcharbonnier** [comment]
sure !

**Comment by AgustinCB** [comment]
It should be pushed now.

**Pull request merged**
